import os

# Environment variables
RTMP_MEDIA_SERVER = os.getenv("RTMP_MEDIA_SERVER", "rtmp://localhost:1935")
NAMESPACE = "/default"

# Frame processing constants
DEFAULT_FRAME_TIMEOUT = 5
DEFAULT_RECORD_DURATION = 10
DEFAULT_FRAME_INTERVAL = 30
DEFAULT_UNSAFE_RATIO_THRESHOLD = 0.7
DEFAULT_EVENT_COOLDOWN = 30
MAX_RECONNECT_WAIT = 60
MAX_BUFFER_SIZE = 2
MAX_FRAME_QUEUE_SIZE = 10
FPS_QUEUE_SIZE = 30
INFERENCE_INTERVAL = 1 / 5
